### ISSUE TITLE
Add optional platform layers.

### ISSUE THREAD

**Issue by SasLuca** [SasLuca/rayfork#12]
Since rayfork aims to not provide any platform layers it can be very useful to provide optional ones or examples that developers can use. 

Particularly on platforms like iOS and Android where it can be harder to find libraries that provide platform layer support.

**Comment by pixelblender** [comment]
maybe this could be an option? https://github.com/brackeen/glfm

**Comment by SasLuca** [comment]
This could work for an example.
So far we have examples with GLFW, sokol_app, GLAD and SDL.
I will look into this :D

**Comment by SasLuca** [comment]
I decided to make an optional header, maybe something like `rayfork_ez.h` which will pack sokol-app and some other utility functions as a quick way to get a platform layer going.
