### ISSUE TITLE
Remove stdarg.h

### ISSUE THREAD

**Issue by SasLuca** [SasLuca/rayfork#16]
Currently, `stdarg.h` is included just for the logging callback.

We can remove it and have the users of the logging function create a string on the stack with the data formatted inside it and pass that to `rf_trace_log`.

Example: 
```cpp
rf_trace_log(rf_ctx, rf_log_info, "[TEX ID %i] Default font loaded successfully", rf_ctx->default_font.texture.id);
```
Would become this:
```cpp
char log_buffer[1024]; //Or some smaller value
snprintf(log_buffer, 1024, "[TEX ID %i] Default font loaded successfully", rf_ctx->default_font.texture.id);
rf_trace_log(rf_ctx, rf_log_info, log_buffer);
```

# Rationale
We want to minimise the amount of includes, especially in the `interface` region. If we can remove all includes in the `interface` region that would be even better.

**Comment by SasLuca** [comment]
Done 67a2c5514dab6d11af63a812d27fab5b0a0c0a77
Also changed the logging to use macros that the user can redefine.

**Comment by raysan5** [comment]
This is a good improvement, stdarg inclusion was added later on by user contribution... and I'm also thinking about removing it.

**Comment by SasLuca** [comment]
Apparently I missed a couple of places where we use `va_list`. I removed those and also removed `_rf_text_format` and replaced it with `snprintf` instead: ade8cb37a43752d0923a1a5ec35a84dddf1239bc
