### ISSUE TITLE
Project has no LICENSE assigned

### ISSUE THREAD

**Issue by raysan5** [SasLuca/rayfork#23]
It would be great to have a permissive license assigned, for example MIT.

**Comment by SasLuca** [comment]
Definitely, my bad for not adding one.
I will add a license, probably the same one as for the STB libraries: https://github.com/nothings/stb/blob/master/LICENSE

**Comment by raysan5** [comment]
That's a very good one.

**Comment by IamRifki** [comment]
I agree, either 0BSD, or Dual licensed MIT and Unlicense.

**Comment by SasLuca** [comment]
Added Unlicense
