### ISSUE TITLE
Project logo?

### ISSUE THREAD

**Issue by raysan5** [SasLuca/rayfork#24]
It would be nice to have a logo for the project, experience show me that projects with a representative logo become more popular. :)

**Comment by SasLuca** [comment]
![image](https://user-images.githubusercontent.com/15983269/74030029-efcf6780-49a5-11ea-913a-2abcd8e2d86f.png)

I have this wonderful logo prepared for the 1.0 release ;)
I've been working a lot on a local branch for a big update (maybe I should focus on more incremental updates in the future) so I hope people look forward to that, aiming to release at least a 0.9 version this week.

**Comment by raysan5** [comment]
@SasLuca hehehe... nice! :D

About updates, the same happens with raylib, I prefer to work towards a big release instead of small ones... and you become over-saturated with things to close... every new release I promise myself I'll change that pattern... it never happened...

**Comment by SasLuca** [comment]
Added a very lovely logo :)

![logo](https://user-images.githubusercontent.com/15983269/83981758-ad4c7600-a918-11ea-8a56-1d80350867f0.jpg)
