### ISSUE TITLE
frame_time is zero

### ISSUE THREAD

**Issue by abeimler** [SasLuca/rayfork#25]
Hi there,
I have some problems with `frame_time` in `rf_context`.

 1. `rf_get_frame_time` is not impl. (error: undefined reference to `rf_get_frame_time')
 2. rf_ctx.frame_time is zero

I used the basic_shapes example for testing.
```cpp
void on_frame(void) {
  // error: undefined reference to `rf_get_frame_time'
  //printf("frame time %f\n", rf_get_frame_time());
  
  printf("frame time %f %f %f %f %f\n", rf_ctx.target_time, rf_ctx.current_time,
         rf_ctx.draw_time, rf_ctx.previous_time, rf_ctx.frame_time);
  printf("fps %d\n", rf_get_fps());
         
  rf_begin_drawing();
  //...
  rf_draw_fps(5, 5);

  rf_end_drawing();
}
```

**Output:**
```bash
frame time 0.016667 22425.000000 0.000000 22425.000000 0.000000
fps -2147483648
frame time 0.016667 22425.000000 0.000000 22425.000000 0.000000
fps -2147483648
frame time 0.016667 22426.000000 0.000000 22426.000000 1.000000
fps 1
frame time 0.016667 22426.000000 0.000000 22426.000000 0.000000
fps -2147483648
...
frame time 0.016667 22429.000000 0.000000 22429.000000 0.000000
fps -2147483648
```

3. `rf_draw_fps` is also wrong
![image](https://user-images.githubusercontent.com/22779737/74165373-4a2a2b80-4c25-11ea-9997-8a2d342ed018.png)

**Environment:**
 - branch: master
 - Arch Linux (64-Bit) (4.19 kernel)
 - AMD CPU, GeForce GTX 970 Graphic
 - compiled with cmake 3.16, gcc 9.2.0

**Comment by SasLuca** [comment]
Hi, this is fixed in the rayfork 0.9 update which will be out in a couple of days.
rayfork is not yet stable for development, I recommend you wait for the latest update which will be later this week. After that update I plan on keeping rayfork mostly API compatible.
